### ISSUE TITLE
Bug: \bar{0} after symmetrise

### ISSUE THREAD

**Issue by matheusGariglio** [mtex-toolbox/mtex#694] opened 2021-01-12 12:47 UTC
Hi!

I'm currently having a little problem while plotting IPFs for the HCP titanium alpha phase.

The orientations seem to be write, but I'm getting -0 values, as you can see below :
```
ebsd2 = ebsd;
IPFXa = ipfHSVKey(ebsd2('Alpha'));
figure; plot(IPFXa)
```
![image](https://user-images.githubusercontent.com/77332633/104315789-c71bf000-54db-11eb-8877-ae4dc5588614.png)

This also happens when doing:
```
o_A = ebsd2('Alpha').orientations;
figure; plotIPDF(o_A,[vector3d.X,vector3d.Y,vector3d.Z],'contourf')
```

![image](https://user-images.githubusercontent.com/77332633/104313574-8078c680-54d8-11eb-996c-ecf2cef4f3c8.png)

I'm using the 5.5.0 version, but I've also tested it on the latest version.

I would like to know if this is some kind of bug or if it is something linked to my coding.

I'm sending you one example of my data in the following link : [https://cloud.mines-paristech.fr/index.php/s/fOHrkiBmfURtqEU]

Kind regards,
Matheus

**Comment by kilir** [comment] 2021-01-12 12:56
Hi,
I'm not entirely sure what you'd like to achieve. Do you want to plot an EBSD map or colored points? Or something else? 
You data loads fine and ipf plots or maps are plotting fine for me.
Cheers,
Rüdiger

**Comment by matheusGariglio** [comment] 2021-01-12 13:00
Hi Rüdiger,

First of all, thanks for your quick answer and happy new year :)

Actually, the data is fine for me. The only problem are those negative zeros appearing in the triangle edges, as [-00-01] instead of simply [0001]. Is this some kind of bug?

Cheers,
Matheus

**Comment by kilir** [comment] 2021-01-12 14:18
Hi Matheus,
sorry I did not get this, now I see what you mean.

<img width="1384" alt="ipfplot" src="https://user-images.githubusercontent.com/11697557/104325198-a6a66280-54e8-11eb-85d1-14c3a53f7e69.png">
<img width="403" alt="key" src="https://user-images.githubusercontent.com/11697557/104325459-f553fc80-54e8-11eb-8c2c-866d6b03220f.png">

Above is what I get. 

What does  `plotHKL(o_A.cs)` give ?

Cheers,
Rüdiger

**Comment by matheusGariglio** [comment] 2021-01-12 14:26
Hi Rüdiger,

No worries.

When I do exactly as you said, I get : 
>> plotHKL(o_A.cs)
```
Unrecognized method, property, or field 'cs' for class 'orientation'.

Error in rotation/subsref (line 22)
      [varargout{1:nargout}] = builtin('subsref',r,s);
```

However, doing CS in capital letters :

`>> plotHKL(o_A.CS)`

I get :
![image](https://user-images.githubusercontent.com/77332633/104326727-56c89b00-54ea-11eb-8ca9-d13680e8cd35.png)

**Comment by kilir** [comment] 2021-01-12 16:40
Hi,
sorry, the `cs` instead of `CS` was of course a typo. I can confirm that your observation relates to a bug when directions are excessively potted on top of each other and should be fixed soon.
```plot(Miller(0,0,0,1,crystalSymmetry('622'),'uvw'),'labeled','symmetrised','lower')```
Cheers,
Rüdiger

**Comment by matheusGariglio** [comment] 2021-01-12 16:47
Hi Rüdiger,

Yes, I just thought that maybe in the latest version (5.6.0) it was changed to cs.

Ok, thank you!

Cheers,
Matheus

**Comment by kilir** [comment] 2021-01-12 17:22
Hi,
I reopen this because I think it's a bug related to a rounding during symmetrise.  `\bar{0}` should not be assigned if `0` is sufficiently close to zero. Didn't we have something similar before (https://github.com/mtex-toolbox/mtex/discussions/575)?

To reproduce the issue:
```
h = symmetrise(Miller(0,0,0,1,crystalSymmetry('622')),'unique')
char(h(2),'LaTeX')

'$(\bar{0}\bar{0}0\bar{1})$'

```




Cheers,
Rüdiger

**Closed** 2021-01-12 18:02 UTC
Labels: bug :beetle:

**Comment by matheusGariglio** [comment] 2021-01-12 18:09
Hi Rüdiger,

I've tested after this bug fix and it's working fine for me.

Thanks a lot!

Cheers,
Matheus
